<a href="https://colab.research.google.com/github/Keerthiga-I/PYTHON-CODE/blob/PYTHON-LEVELS/numpy_basis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CREATE FIRST ARRAY

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
a.shape

(5,)

In [6]:
type(a)

numpy.ndarray

CREATE 2D ARRAY

In [20]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])


In [21]:
arr


array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [22]:
arr.shape

(2, 5)

CREATE 3D ARRAY

In [34]:
arr_1 = np.array([[[1,2,3,4,5],[6,7,8,9,0],[9,8,7,6,5]],[[4,3,2,1,0],[1,2,3,4,5],[4,5,6,7,8]],[[9,0,7,6,5],[2,3,4,5,6],[1,3,5,7,9]]])

In [41]:
arr_1

array([[[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0],
        [9, 8, 7, 6, 5]],

       [[4, 3, 2, 1, 0],
        [1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8]],

       [[9, 0, 7, 6, 5],
        [2, 3, 4, 5, 6],
        [1, 3, 5, 7, 9]]])

In [42]:
arr_1.shape

(3, 3, 5)

In [43]:
arr_1[1,1,3]

np.int64(4)

In [38]:
arr_1[1,0:2,2:4]

array([[2, 1],
       [3, 4]])

In [45]:
arr_1.dtype

dtype('int64')

In [46]:
arr.shape

(2, 5)

Function of NP Array


1.ARANGE

In [48]:
arr_1 = np.arange(10,100,5)
arr_1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [50]:
arr_1 = arr_1.reshape(3,3,2)
arr_1

array([[[10, 15],
        [20, 25],
        [30, 35]],

       [[40, 45],
        [50, 55],
        [60, 65]],

       [[70, 75],
        [80, 85],
        [90, 95]]])

2.Linspace

In [51]:
arr_1 = np.linspace(1,100,num=18).astype('int')
arr_1

array([  1,   6,  12,  18,  24,  30,  35,  41,  47,  53,  59,  65,  70,
        76,  82,  88,  94, 100])

In [53]:
arr_1.reshape(3,6)

array([[  1,   6,  12,  18,  24,  30],
       [ 35,  41,  47,  53,  59,  65],
       [ 70,  76,  82,  88,  94, 100]])

3.ONES

In [56]:
arr_1 = np.ones(25).astype('int')
arr_1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [57]:
arr_1 = arr_1.reshape(5,5)
arr_1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
arr_2 = np.zeros(15).astype('int')
arr_2


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
arr_2 = arr_2.reshape(3,5)
arr_2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [63]:
arr3 = np.arange(30)
arr3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [74]:
arr3.reshape(2,5,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])